[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.virtualenv",
  "gcc"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r backend/requirements.txt",
  "python -c \"import nltk; nltk.download('punkt')\"",
  "python -c \"from transformers import CLIPProcessor, CLIPModel; CLIPModel.from_pretrained('openai/clip-vit-base-patch32'); CLIPProcessor.from_pretrained('openai/clip-vit-base-patch32')\""
]

[start]
cmd = ". /opt/venv/bin/activate && cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT --log-level debug"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100