[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "gcc",
  "nodejs-18_x"
]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "python -c \"import nltk; nltk.download('punkt')\"",
  "python -c \"from transformers import CLIPProcessor, CLIPModel; CLIPModel.from_pretrained('openai/clip-vit-base-patch32'); CLIPProcessor.from_pretrained('openai/clip-vit-base-patch32')\""
]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"