[build]
builder = "nixpacks"
buildCommand = "cd backend && python -m pip install -r requirements.txt --no-cache-dir --break-system-packages"

[deploy]
startCommand = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT --log-level debug"
healthcheckPath = "/health"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[variables]
PYTHONUNBUFFERED = "1"