[build]
builder = "nixpacks"
buildCommand = "echo 'Building RAG Art Application'"

[deploy]
startCommand = "python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs-18_x", "yarn"]